name: Diagnostics

on:
  push:

jobs:
  diagnostics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run diagnostics
      run: python diagnostics.py
      env:
        BOT_NAME: ${{ vars.BOT_NAME }}
        BOT_VERSION: ${{ vars.BOT_VERSION }}
        BOT_URL: ${{ vars.BOT_URL }}
        BOT_EMAIL: ${{ vars.BOT_EMAIL }}